### ISSUE TITLE
is this

### ISSUE THREAD

**Issue by AlexHelo** [MarioJim/dotfiles#2]
manjaro????????????????????????????????????

**Comment by AlexHelo** [comment]
is it?

**Comment by Lars17S** [comment]
haha retardddddddddddddddd

**Comment by AlexHelo** [comment]
check[this]out(https://github.com/AlexHelo/InteractivePractice2_Top_down_parsing)

**Comment by MarioJim** [comment]
> manjaro????????????????????????????????????

nah broooooooo

btw, i use arch

**Comment by AlexHelo** [comment]
@Mauville
